### ISSUE TITLE
OS X: closing the window unloads vector

### ISSUE THREAD

**Issue by jansol** [krisak/vector-electron-desktop#1]
On OS X, applications can stay open in the background even when their window is closed. Vector-electron-desktop currently stays "open" but apparently unloads the vector page, dropping the connection. Notifications are not received in this state either, confirming my suspicion.

For other platforms I think "minimize to tray" is the closest common behaviour.

**Comment by iskrisis** [comment]
I knwo about this. I tried to implement just window hide but wasnt succesful. I will try again.

Other platforms should just close which is normal on windows (and its working like that now).

**Comment by anatomism** [comment]
I've played with this using every possible combination of lines from Stack Overflow ;). Doesn't work for me unfortunately

**Comment by iskrisis** [comment]
@anatomism So you have tried to find solution to hiding too? I guess it is time to ask people from electron comunity how to do this.

**Comment by anatomism** [comment]
@krisak Yea. About 6 different combos, not seem to work

What would be nice as well is transparent title bar, but able to move the window. From what I've read there needs to be code changes (WebKit) rather than within Electron main.js itself

**Comment by iskrisis** [comment]
@anatomism i tried lot of the possibilities as well. Maybe we should hunt down some open-source electron app that does that and steal the code.

What do you mean by transparent title bar? We can hide it completely (it stops to look macky i tried) but then the problem is we need to touch vector itself because you need to implement the stop lights - the close, minimize, fullscreen buttons yourself. There is not realy good way to inject that into the render thread without touching vector.

**Comment by anatomism** [comment]
Check https://github.com/RocketChat/Rocket.Chat.Electron

I haven't tested the functions however

**Comment by jansol** [comment]
closing as obsolete
